Revert "Make libutils test compile on the host"
Fails mac build: "system/core/include/utils/Looper.h:25:10: fatal error: 'sys/epoll.h' file not found"

This reverts commit afa891e85e7d8f852d0eab706d44226b6fdfedd1.

Change-Id: Ib558b8f5a303b55ab32a399d338d8aac0fae32b2